# Generated by Django 5.2.4 on 2025-09-16 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('invitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='app1.invitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('invitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='app1.invitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('google_maps_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.AddField(
            model_name='invitado',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitados', to='app1.mesa'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ubicacion'),
        ),
    ]
