# Generated by Django 5.2.4 on 2025-09-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_invitacion_invitado_mesa_ubicacion_delete_prueba_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitado',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='invitado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invitado',
            name='invitacion',
        ),
        migrations.RemoveField(
            model_name='invitado',
            name='mesa',
        ),
        migrations.AddField(
            model_name='invitacion',
            name='invitados',
            field=models.ManyToManyField(blank=True, related_name='invitaciones', to='app1.invitado'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='numero_mesa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
