# Generated by Django 5.2.4 on 2025-09-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_invitado_confirmado_remove_invitado_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='invitacion',
        ),
        migrations.AddField(
            model_name='invitacion',
            name='mesas',
            field=models.ManyToManyField(blank=True, related_name='invitaciones', to='app1.mesa'),
        ),
    ]
