# Generated by Django 5.2.4 on 2025-09-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_mesa_invitacion_invitacion_mesas'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
