# Generated by Django 5.2.6 on 2025-09-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_fechaevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
