# Generated by Django 5.2.6 on 2025-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_invitado_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
