# Generated by Django 5.2.6 on 2025-09-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_invitacion_confirmada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='app1.invitacion')),
            ],
        ),
    ]
