# Generated by Django 5.1.6 on 2025-11-17 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechaevento',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Ubicación global del evento (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.ubicacion'),
        ),
    ]
